// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repositories/collections.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"
	models "w3st/domain/models"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCollectionsRepository is a mock of CollectionsRepository interface.
type MockCollectionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionsRepositoryMockRecorder
}

// MockCollectionsRepositoryMockRecorder is the mock recorder for MockCollectionsRepository.
type MockCollectionsRepositoryMockRecorder struct {
	mock *MockCollectionsRepository
}

// NewMockCollectionsRepository creates a new mock instance.
func NewMockCollectionsRepository(ctrl *gomock.Controller) *MockCollectionsRepository {
	mock := &MockCollectionsRepository{ctrl: ctrl}
	mock.recorder = &MockCollectionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionsRepository) EXPECT() *MockCollectionsRepositoryMockRecorder {
	return m.recorder
}

// CreateCollection mocks base method.
func (m *MockCollectionsRepository) CreateCollection(newCollection *models.ApiCollection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", newCollection)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockCollectionsRepositoryMockRecorder) CreateCollection(newCollection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockCollectionsRepository)(nil).CreateCollection), newCollection)
}

// GetCollectionByUserId mocks base method.
func (m *MockCollectionsRepository) GetCollectionByUserId(userId uuid.UUID) ([]models.ApiCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionByUserId", userId)
	ret0, _ := ret[0].([]models.ApiCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionByUserId indicates an expected call of GetCollectionByUserId.
func (mr *MockCollectionsRepositoryMockRecorder) GetCollectionByUserId(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionByUserId", reflect.TypeOf((*MockCollectionsRepository)(nil).GetCollectionByUserId), userId)
}

// GetCollectionsByCollectionId mocks base method.
func (m *MockCollectionsRepository) GetCollectionsByCollectionId(collectionId int, userId uuid.UUID) (*models.ApiCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionsByCollectionId", collectionId, userId)
	ret0, _ := ret[0].(*models.ApiCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionsByCollectionId indicates an expected call of GetCollectionsByCollectionId.
func (mr *MockCollectionsRepositoryMockRecorder) GetCollectionsByCollectionId(collectionId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionsByCollectionId", reflect.TypeOf((*MockCollectionsRepository)(nil).GetCollectionsByCollectionId), collectionId, userId)
}
