version: "2"

run:
  timeout: 5m

linters:
  # 全ての linter を無効化
  disable-all: true

  # 指定した linter のみ有効化
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - misspell
  issues:
    exclude-rules:
      #　testファイルを除外
      - path: _test\.go
        linters:
          - gocyclo
          - gosec
          - exhaustruct
#    除外するディレクトリ
    exclude-dirs:
      - mocks
      - tmp

    # 除外するファイル
    exclude-files:
      - cover.out
      - cover.html
      - .air.toml
