run:
  deadline: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-use-default: false

  exclude-rules:
    - path: ".air.toml"
      linters:
        - lll
    - path: "cover.*"
      linters:
        - lll
    - path: "internal/.*"
      linters:
        - lll
    - path: ".*_test.go"
      linters:
        - dupl
linters:
  enable:
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - promlinter
    - staticcheck
    - tenv
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
linters-settings:
  copyloopvar:
    check-alias: true
  goconst:
    ignore-strings: "true"
  gocritic:
    disabled-checks:
      - assignOp
      - ifElseChain
  testifylint:
    enable-all: true